<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Jumat,18-08-23_w-full max-w-full h-auto</name>
   <tag></tag>
   <elementGuidId>56659bba-e48b-4af5-942d-cc31df8816ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-full.max-w-full.h-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://media.shafiq.id/public/news/raih-merdeka-secara-finansial-dengan-metode-smart1.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7a140942-ad10-4163-b4df-4bb0b7412799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.shafiq.id/public/news/raih-merdeka-secara-finansial-dengan-metode-smart1.jpg</value>
      <webElementGuid>3e8ebf2c-c8b2-4d68-932e-f74cc7344a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full max-w-full h-auto</value>
      <webElementGuid>29bf4e36-22c7-49cd-84c0-e991b37b50b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js sizes customelements history pointerevents postmessage postmessage-structuredclones webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers&quot;]/body[1]/div[@class=&quot;site-content font-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mb-6&quot;]/img[@class=&quot;w-full max-w-full h-auto&quot;]</value>
      <webElementGuid>b519ed4c-82e2-4fc2-8276-8d6eb4b9b30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.shafiq.id/public/news/raih-merdeka-secara-finansial-dengan-metode-smart1.jpg')]</value>
      <webElementGuid>0acb44e9-3d71-4ac6-ad19-887107b16d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>cedc8845-4828-44d4-934a-c2aaa318e742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.shafiq.id/public/news/raih-merdeka-secara-finansial-dengan-metode-smart1.jpg']</value>
      <webElementGuid>4811f6e7-6ca0-4936-9f2b-6c35f5036bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
