<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat Lebih Banyak</name>
   <tag></tag>
   <elementGuidId>c5883667-afe9-41eb-8873-26c020a1c149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portfolio-feed']/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e09656b6-f4dd-4ad8-b4c1-3edbcc2570f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>fetchData()</value>
      <webElementGuid>f545b760-2625-4dc1-9dd5-48b60c0ce771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0 sm:hover:bg-primary sm:hover:text-white bg-primary text-white sm:text-primary sm:bg-white sm:border sm:border-primary rounded-md w-[157px] h-[43px]</value>
      <webElementGuid>dff275d1-4883-45e1-a89e-7c3f750a90ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Lebih Banyak</value>
      <webElementGuid>e495f6e0-7770-43d5-b7c3-0bd79bc7759a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfolio-feed&quot;)/div[@class=&quot;mt-2 md:mt-6 text-center&quot;]/button[@class=&quot;border-0 sm:hover:bg-primary sm:hover:text-white bg-primary text-white sm:text-primary sm:bg-white sm:border sm:border-primary rounded-md w-[157px] h-[43px]&quot;]</value>
      <webElementGuid>ef8d2a1d-e4c4-4293-9e48-89d4c80315bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portfolio-feed']/div[3]/button</value>
      <webElementGuid>97382ee3-f584-414d-ae1b-79ed6f698ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data belum tersedia atau data dengan kriteria tersebut tidak ditemukan'])[1]/following::button[1]</value>
      <webElementGuid>49476be6-f70f-4929-a986-33ba44ea4905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Investasi'])[2]/following::button[4]</value>
      <webElementGuid>b3ec7294-9d33-436a-b205-13781fe2a942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::button[1]</value>
      <webElementGuid>45e39132-e74c-4be6-85ba-805675f8b32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Kontak dan Bantuan'])[1]/preceding::button[1]</value>
      <webElementGuid>3c33877f-5bc7-4695-9fd7-58962302c321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Lebih Banyak']/parent::*</value>
      <webElementGuid>aed1cb7b-14f9-47fb-a2ec-9bf6b9e2ce2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>44aba72f-6a2f-4d4b-b344-f895ff914686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lihat Lebih Banyak' or . = 'Lihat Lebih Banyak')]</value>
      <webElementGuid>b3eeaba9-861a-4ee0-9134-fd36ac09ff49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
