<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daftar Investasi_search_keywords</name>
   <tag></tag>
   <elementGuidId>3b3b72c9-531b-4821-891e-e1e0b642794d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search_keywords&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='search_keywords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7936d80-88a2-422b-8151-eeb4b77aa929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@keydown.enter</name>
      <type>Main</type>
      <value>emitKeywords($dispatch)</value>
      <webElementGuid>2ee9a047-1eda-4d04-9b45-e977f8f7398d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>keywords</value>
      <webElementGuid>1d56200a-0d90-4a7a-b258-49958b9275fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>190f40aa-9bce-49e8-b3ed-8cce56a2b87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_keywords</value>
      <webElementGuid>be8c5773-7996-4993-a7d7-14adcce91e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7fac8e28-929d-47ed-a01e-646d47e1b021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>f37d9d12-f6a5-4f76-ac64-d262bfcdf38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfolio-feed-panel&quot;)/div[@class=&quot;[ portfolio-feed-panel__container ] flex flex-wrap py-3&quot;]/div[@class=&quot;w-7/12 md:w-auto lg:w-1/3 mb-2 md:mb-0&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>760fb8c9-e9ab-4c6a-9ce1-15a91c63fa2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search_keywords']</value>
      <webElementGuid>c7ef7030-2cf7-4c25-853d-17b46f6f0d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portfolio-feed-panel']/div/div/div/input</value>
      <webElementGuid>a3d2fd98-e448-46bf-9a79-5a5ee8550bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>48e97599-5c2e-442b-a40f-04d24a2a0341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_keywords' and @placeholder = 'Cari']</value>
      <webElementGuid>3f50b1c3-6a68-4318-8f0c-b25d1e3c0ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
