<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_KebijakanPrivasi_portfolio-slider</name>
   <tag></tag>
   <elementGuidId>fb628ced-3d1a-4c25-b9e6-a65d68f4730f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#portfolio-slider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='portfolio-slider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>802c1354-6ab7-4df4-b6ec-57b194071927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>portfolio-slider</value>
      <webElementGuid>1a08a9c1-427d-494d-ae41-4286b16cc34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portfolio-slider col-12 col-lg-7 mb-4 lg:mb-0</value>
      <webElementGuid>93407dd2-5298-43ea-b674-58177d9f525d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfolio-slider&quot;)</value>
      <webElementGuid>a41d410e-1b1d-4360-9f33-08ba8cfb011a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='portfolio-slider']</value>
      <webElementGuid>127a06ec-d56f-4af8-b43d-a3720f47a41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERDAGANGAN BESAR DAN ECERAN; REPARASI DAN PERAWATAN MOBIL DAN SEPEDA MOTOR'])[1]/preceding::section[1]</value>
      <webElementGuid>91a876f4-7ebf-454d-9741-0dfa52106357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/preceding::section[1]</value>
      <webElementGuid>66209430-2009-42ff-ae8a-dbfce17e5199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>63e3d396-9451-4d8d-a41b-677d5f19cc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'portfolio-slider']</value>
      <webElementGuid>c242ab02-8d7b-4c22-adb1-e979745cc738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
