<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masuk_hamburger-box</name>
   <tag></tag>
   <elementGuidId>ac25d530-15ac-4662-9615-7abe7f3a9e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.hamburger-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='offcanvas']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc1a8f23-b6b4-4bf0-90b0-96b58b18de06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger-box</value>
      <webElementGuid>73569ca2-a869-460b-a71d-46640a76cf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;[ shafiq-navbar ] navbar navbar-expand-lg&quot;]/button[@id=&quot;offcanvas&quot;]/span[@class=&quot;hamburger-box&quot;]</value>
      <webElementGuid>f421032f-8c82-4672-a64a-2c858582a538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='offcanvas']/span</value>
      <webElementGuid>00af0461-59f6-4ca8-a143-46f40930744b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::span[2]</value>
      <webElementGuid>22e90c36-2eb5-42bc-928c-1051002340e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::span[3]</value>
      <webElementGuid>6f125f52-c9e9-42ba-af68-2c2a888b3b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>1591e9b1-ea25-4d0e-90dd-3a103bc9d010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
