<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Penerbit</name>
   <tag></tag>
   <elementGuidId>1d7a1983-f487-41b7-9095-f7f3c8dc21ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Penerbit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00d322d9-4fe9-4c99-956b-4c8c4dba16af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-2 rounded-xxl</value>
      <webElementGuid>32b8e249-0532-4c7f-a90f-4102e01e52bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.shafiq.id/faq/penerbit</value>
      <webElementGuid>58c1e2d0-67c9-47dc-b19b-c46d728889d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penerbit</value>
      <webElementGuid>7807081e-2dae-4728-bfa4-9e388dbfe91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js sizes customelements history pointerevents postmessage postmessage-structuredclones webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers&quot;]/body[1]/div[@class=&quot;site-content font-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mb-8&quot;]/div[@class=&quot;flex justify-center col-12&quot;]/div[@class=&quot;flex items-center px-2 py-2 mx-auto bg-gray-200 rounded-xxl&quot;]/a[@class=&quot;px-3 py-2 rounded-xxl&quot;]</value>
      <webElementGuid>d6fbc44f-29a3-421e-ba84-a7b91688634e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Penerbit')]</value>
      <webElementGuid>d2ab13d8-4936-470d-8233-549fa0b764f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemodal'])[1]/following::a[1]</value>
      <webElementGuid>ca28891b-157c-404b-ade7-c52574064ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umum'])[1]/following::a[2]</value>
      <webElementGuid>b10f4cff-147c-483f-8eb4-3bcd0c34b0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya apa saja yang harus dibayarkan jika ingin berinvestasi di SHAFIQ?'])[1]/preceding::a[1]</value>
      <webElementGuid>c77c8548-32df-4859-883b-0b2f936f5e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikut tabel rangkuman biaya investasi di SHAFIQ'])[1]/preceding::a[1]</value>
      <webElementGuid>a68eb6b9-5cf4-45a8-b466-c6b9e8530b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penerbit']/parent::*</value>
      <webElementGuid>9594a206-119d-4dfc-bb7b-e517bd57c6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.shafiq.id/faq/penerbit')]</value>
      <webElementGuid>3fabf38d-791f-4eab-a8ca-dda1b6d232c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>b3a22520-8517-44d7-9306-a7714a8bccec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.shafiq.id/faq/penerbit' and (text() = 'Penerbit' or . = 'Penerbit')]</value>
      <webElementGuid>9b384dd6-31f3-4213-9044-8c66e01e67ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
