<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pemodal</name>
   <tag></tag>
   <elementGuidId>30d427b0-590c-42c4-8d10-36b2a44ff664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Pemodal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6df3542d-70e4-4c37-a309-03fd28e186a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-2 rounded-xxl</value>
      <webElementGuid>a5ddc234-7954-4faa-b82e-ffa09b33c807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.shafiq.id/faq/pemodal</value>
      <webElementGuid>c62171d7-a02b-4f89-b038-f410926b67b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pemodal</value>
      <webElementGuid>8037ab9d-e466-4f3b-a3df-58c9509a6c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js sizes customelements history pointerevents postmessage postmessage-structuredclones webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers&quot;]/body[1]/div[@class=&quot;site-content font-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row mb-8&quot;]/div[@class=&quot;flex justify-center col-12&quot;]/div[@class=&quot;flex items-center px-2 py-2 mx-auto bg-gray-200 rounded-xxl&quot;]/a[@class=&quot;px-3 py-2 rounded-xxl&quot;]</value>
      <webElementGuid>aa1df9b4-03a9-4cd3-95df-820bee91adaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pemodal')]</value>
      <webElementGuid>5dbeee2b-9c11-46bc-8ee5-a7854d747a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umum'])[1]/following::a[1]</value>
      <webElementGuid>fd226e68-3b6b-4819-8857-dfecc4c56819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Asked Questions (F.A.Q)'])[1]/following::a[2]</value>
      <webElementGuid>94196f8d-7327-422a-b98f-cdd5387b5050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerbit'])[1]/preceding::a[1]</value>
      <webElementGuid>c27a5138-586a-4e77-9da3-5713c08cc4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa itu SHAFIQ?'])[1]/preceding::a[2]</value>
      <webElementGuid>705d4a2c-961f-40c6-8c46-1834e3fd2294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pemodal']/parent::*</value>
      <webElementGuid>91ea8400-c850-4d3a-ba23-408e318a073e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.shafiq.id/faq/pemodal')]</value>
      <webElementGuid>0987102e-88bb-4c2f-b358-1cd78e94b086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>7a3ef94a-304b-469e-b566-28bf54d8092d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.shafiq.id/faq/pemodal' and (text() = 'Pemodal' or . = 'Pemodal')]</value>
      <webElementGuid>b68bc333-2e0a-46be-84ad-4f00705a8775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
