<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masuk_hamburger-inner</name>
   <tag></tag>
   <elementGuidId>eed6e196-da1d-48c5-be9e-25c76e4aab08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.hamburger-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='offcanvas']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8664c8c-4042-49a6-9e5b-c24973ddf846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger-inner</value>
      <webElementGuid>620810e9-8a9b-475c-a555-2faaf48abe51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;[ shafiq-navbar ] navbar navbar-expand-lg&quot;]/button[@id=&quot;offcanvas&quot;]/span[@class=&quot;hamburger-box&quot;]/span[@class=&quot;hamburger-inner&quot;]</value>
      <webElementGuid>75994b5d-8087-4ec2-b969-9337c29365a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='offcanvas']/span/span</value>
      <webElementGuid>a11d1a8f-6429-460e-9a21-130eb512b421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>0682f0b8-9a72-4a68-975d-9fa056cdd0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
